#!/usr/bin/env python3
import json

for fname, jsvar in [("videos.json", None), ("videos-data.js", "window.VIDEOS_DATA")]:
    if fname == "videos.json":
        with open(fname, encoding="utf-8") as f:
            data = json.load(f)
        removed = data["threads"].pop(0)
        print(
            f"Removed: \"{removed['title']}\" ({len(removed.get('videos',[]))} videos)"
        )
        data["total"] = sum(len(t.get("videos", [])) for t in data["threads"])
        with open(fname, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(
            f"videos.json: {len(data['threads'])} threads, {data['total']} total videos"
        )
    else:
        with open("videos-data.js", "w", encoding="utf-8") as f:
            f.write("// Auto-generated by crawl_videos.py — do not edit manually\n")
            f.write("window.VIDEOS_DATA = ")
            json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
            f.write(";\n")
        print("videos-data.js updated")
