// Auto-generated by indexlocal.html
window.TAGS_DATA = {
  "adminId": "xam_mm4q6g9r_rih6wk2",
  "tags": [
    "bikini",
    "bj",
    "chat-sex",
    "doggy",
    "gái-xinh",
    "make-love",
    "nude",
    "trash"
  ],
  "items": {
    "chat-sex": [
      283807
    ],
    "nude": [
      283844,
      283843,
      283842,
      283841,
      283840,
      283839,
      283845,
      283846,
      283847,
      283848,
      283849,
      283850,
      283851,
      283852,
      283853,
      283854,
      283855,
      283856,
      283858,
      283859,
      283860,
      283861,
      283862,
      283863,
      283864,
      283865,
      283867,
      283871,
      283875,
      283876
    ],
    "make-love": [
      283869
    ],
    "bj": [
      283873,
      283874
    ],
    "gái-xinh": [
      622989,
      622988
    ],
    "bikini": [],
    "trash": [],
    "doggy": []
  }
};
