// Auto-generated by indexlocal.html
window.TAGS_DATA = {
  "adminId": "xam_mm4q6g9r_rih6wk2",
  "tags": [
    "bikini",
    "bj",
    "chat-sex",
    "doggy",
    "girl-xinh",
    "make-love",
    "nude",
    "trash"
  ],
  "items": {
    "chat-sex": [
      283807
    ],
    "nude": [
      283844,
      283843,
      283842,
      283841,
      283840,
      283839,
      283845,
      283846,
      283847,
      283848,
      283849,
      283850,
      283851,
      283852,
      283853,
      283854,
      283855,
      283856,
      283858,
      283859,
      283860,
      283861,
      283862,
      283863,
      283864,
      283865,
      283867,
      283871,
      283875,
      283876
    ],
    "make-love": [
      283869
    ],
    "bj": [
      283873,
      283874
    ],
    "girl-xinh": [
      622989,
      622988
    ],
    "bikini": [],
    "trash": [],
    "doggy": []
  },
  "album_items": {
    "girl-xinh": [
      "https://cdn.save.moe/b/XIDQwm.jpg",
      "https://cdn.save.moe/b/CDt24F.jpg",
      "https://cdn.save.moe/b/ryHs3Ry1.jpg",
      "https://cdn.save.moe/b/dO6PW5h.jpg",
      "https://cdn.save.moe/b/jmCkW5.jpg",
      "https://cdn.save.moe/b/vFx3XV.jpg",
      "https://cdn.save.moe/b/SRDmubb.jpg",
      "https://cdn.save.moe/b/w5jUYJ.jpg",
      "https://cdn.save.moe/b/oZflM5P4.jpg",
      "https://cdn.save.moe/b/VJ0Tpbtj.jpg",
      "https://cdn.save.moe/b/MUOIFQ6J.jpg",
      "https://cdn.save.moe/b/JOWrK36H.jpg",
      "https://cdn.save.moe/b/jt3q8Ed.jpg",
      "https://cdn.save.moe/b/9WLAMtRs.jpg",
      "https://cdn.save.moe/b/MM40fkT.jpg",
      "https://cdn.save.moe/b/iNQejR4o.jpg",
      "https://cdn.save.moe/b/uKZSoYda.jpg",
      "https://cdn.save.moe/b/wHu4ITZ.jpg",
      "https://cdn.save.moe/b/oKMZ6y.jpg",
      "https://cdn.save.moe/b/tdUjiqvj.jpg",
      "https://cdn.save.moe/b/AN3CIlN.jpg",
      "https://cdn.save.moe/b/3YwSJr.jpg",
      "https://cdn.save.moe/b/0KRFT8.jpg",
      "https://cdn.save.moe/b/zkuj8j.jpg",
      "https://cdn.save.moe/b/OL0jyrX.jpg",
      "https://cdn.save.moe/b/BpY9KCb.jpg",
      "https://cdn.save.moe/b/36hbG2Uy.jpg",
      "https://cdn.save.moe/b/W4bQOyZ.jpg",
      "https://cdn.save.moe/b/Ib24ytEN.jpg",
      "https://cdn.save.moe/b/aO6vIZ4r.jpg",
      "https://cdn.save.moe/b/gaSbFZBY.jpg",
      "https://cdn.save.moe/b/v2YqQvo.jpeg",
      "https://cdn.save.moe/b/mvLwKZ.png",
      "https://cdn.save.moe/b/nwaeMg0f.jpg",
      "https://cdn.save.moe/b/7WfE8w5.jpg",
      "https://cdn.save.moe/b/5cr4Dx.jpeg",
      "https://cdn.save.moe/b/MvtpoMj.png"
    ]
  }
};
